import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.About}>
            <h1>About</h1>
            <p>愛知県みよし市出身の2002年生まれ。</p>
      <p>2021年に愛知県立豊田南高等学校を卒業。 その後、静岡大学情報学部情報科学科に入学。</p>
      <p>  現在は大学でプログラミングを勉強中。
アニメを見ることや本を読むことが好き。</p>
          </div>
        </div>
      </main>

    </div>
  )
}
