import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
        @import url(https://fonts.googleapis.com/css2?family=Press+Start+2P&amp;display=swap);
        </style>
      </Head>
      <div  id="top"className={styles.menu}>
        <a href="#top">TOP</a>
        <a href="#about">ABOUT</a>
        <a href="#works">WORKS</a>
      </div>
      <div className={styles.top}>
         portfolio
      </div>
      <main className={styles.main}>
        <div id="about" className={styles.about}>
          <div className={styles.grid}>
            <h1 className={styles.title}>ABOUT</h1>
          <div className={styles.about_text}>
            <strong className={styles.name}>岩村匠真</strong>
            <p>愛知県みよし市出身の2002年生まれ。</p>
            <p>2021年に愛知県立豊田南高等学校を卒業。 その後、静岡大学情報学部情報科学科に入学。</p>
            <p>  現在は大学でプログラミングを勉強中。
            アニメを見ることや本を読むことが好き。</p>
            </div>
            </div>
        </div>
        <div className={styles.works}>
          <div className={styles.grid}>
          <h1 id="works"className={styles.title}>WORKS</h1>
          <div className={styles.workslist}>
            <p className={styles.workstext}>まだないよ。</p>
          </div>
          </div> 
        </div>
      </main>
      <div className={styles.foot}>
      <a href="#top">TOP</a>
      </div>
     
    </div>
  )
}
